name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  BUILD_CONFIGURATION: Debug

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Docker up
      run: |
        sudo docker compose -f docker-compose.yml up -d --build;
        sudo docker ps -a;

    - name: Run healthcheck script
      timeout-minutes: 5
      run: ./scripts/wait-script.sh
      env:
        WAIT_PORTS: 8080,8070,8060,8050

    - name: Run API Tests
      uses: matt-ball/newman-action@master
      with:
        collection: v4/postman/collection.json
        environment: v4/postman/environment.json
        delayRequest: 100
        reporters: '[ "cli" ]'

      
